#!/usr/bin/env python3
"""Does each EDHOC message fit one Tern frame at each region's slowest legal setting?

    python3 analysis/first_contact_fit.py report   # print the tables
    python3 analysis/first_contact_fit.py update   # rewrite the tables in first-contact-fit.md
    python3 analysis/first_contact_fit.py check    # fail if first-contact-fit.md is out of date

The intent for first contact (draft/unicast-security.md, "Not yet specified") is EDHOC (RFC 9528)
with cipher suite 0. This builds each EDHOC message to RFC 9528's structure, byte for byte, with
placeholder bytes where keys, MACs and signatures go: a message's length depends only on its
structure, never on the values in it. Before computing anything it checks itself twice: the
messages it builds for the two traces in RFC 9529 must have the lengths RFC 9529 publishes, and its
time on air must match the reference table the simulator and the firmware both test against
(ternmesh/firmware, tests/lora.c), to the nanosecond.

No dependencies beyond the standard library.
"""

import sys
from pathlib import Path

DOC = Path(__file__).resolve().parent / "first-contact-fit.md"
BEGIN = "<!-- generated by first_contact_fit.py: begin -->"
END = "<!-- generated by first_contact_fit.py: end -->"

# ---------------------------------------------------------------------------------------------
# CBOR (RFC 8949), only as much as EDHOC's messages use


def _head(major: int, n: int) -> bytes:
    if n < 24:
        return bytes([major << 5 | n])
    if n < 0x100:
        return bytes([major << 5 | 24, n])
    if n < 0x10000:
        return bytes([major << 5 | 25]) + n.to_bytes(2, "big")
    return bytes([major << 5 | 26]) + n.to_bytes(4, "big")


def cbor(x) -> bytes:
    if isinstance(x, bool):
        return b"\xf5" if x else b"\xf4"
    if isinstance(x, int):
        return _head(0, x) if x >= 0 else _head(1, -1 - x)
    if isinstance(x, bytes):
        return _head(2, len(x)) + x
    if isinstance(x, str):
        b = x.encode()
        return _head(3, len(b)) + b
    if isinstance(x, list):
        return _head(4, len(x)) + b"".join(cbor(i) for i in x)
    if isinstance(x, dict):
        return _head(5, len(x)) + b"".join(cbor(k) + cbor(v) for k, v in x.items())
    raise TypeError(x)


def _one_byte_int(b: bytes) -> bool:
    """Whether b is the whole CBOR encoding of an integer in -24..23."""
    return len(b) == 1 and (b[0] <= 0x17 or 0x20 <= b[0] <= 0x37)


def conn_id(raw: bytes) -> bytes:
    """A connection identifier as it goes in a message (RFC 9528, 3.3.2): a one-byte identifier
    that is itself the encoding of an integer in -24..23 is sent as that integer, any other as a
    byte string."""
    return raw if _one_byte_int(raw) else cbor(raw)


def id_cred(header: dict) -> bytes:
    """ID_CRED_x as it goes in PLAINTEXT_2 or PLAINTEXT_3. Only {4: kid} is compacted (RFC 9528,
    3.5.3.2): to the kid as a byte string, or to the integer if the kid is a one-byte encoding of
    one. Anything else is the map itself."""
    if list(header) == [4]:
        kid = header[4]
        return kid if _one_byte_int(kid) else cbor(kid)
    return cbor(header)


# ---------------------------------------------------------------------------------------------
# EDHOC messages (RFC 9528, section 5)

# Cipher suite 0: AES-CCM-16-64-128, SHA-256, an 8-byte EDHOC MAC, X25519, EdDSA (Ed25519).
SUITE_0 = 0
ECDH_PUBLIC = 32  # an X25519 public key; for suite 2, P-256's x-coordinate, also 32
SIGNATURE = 64  # Ed25519
EDHOC_MAC = 8  # suite 0's EDHOC MAC length
AEAD_TAG = 8  # AES-CCM-16-64-128

# Which side signs and which uses a static Diffie-Hellman key, by method (RFC 9528, 3.2).
I_SIGNS = {0: True, 1: True, 2: False, 3: False}
R_SIGNS = {0: True, 1: False, 2: True, 3: False}


def message_1(method: int, suites_i, c_i: bytes) -> bytes:
    return cbor(method) + cbor(suites_i) + cbor(bytes(ECDH_PUBLIC)) + conn_id(c_i)


def message_2(method: int, c_r: bytes, id_cred_r: dict) -> bytes:
    sig_or_mac_2 = SIGNATURE if R_SIGNS[method] else EDHOC_MAC
    plaintext_2 = conn_id(c_r) + id_cred(id_cred_r) + cbor(bytes(sig_or_mac_2))
    # CIPHERTEXT_2 is PLAINTEXT_2 XOR a keystream, so the same length.
    return cbor(bytes(ECDH_PUBLIC) + bytes(len(plaintext_2)))


def message_3(method: int, id_cred_i: dict) -> bytes:
    sig_or_mac_3 = SIGNATURE if I_SIGNS[method] else EDHOC_MAC
    plaintext_3 = id_cred(id_cred_i) + cbor(bytes(sig_or_mac_3))
    return cbor(bytes(len(plaintext_3) + AEAD_TAG))


def message_4() -> bytes:
    # PLAINTEXT_4 is only an optional EAD_4, absent here; CIPHERTEXT_4 is the AEAD tag alone.
    return cbor(bytes(AEAD_TAG))


def check_rfc9529():
    """The messages built for RFC 9529's two traces have the lengths it publishes."""
    # Trace 1 (RFC 9529, section 2): method 0, suite 0, X.509 certificates by 'x5t'
    # (ID_CRED = {34: [-15, 8-byte hash]}, 14 bytes), C_I = -14 (h'2d'), C_R = h'18'.
    x5t = {34: [-15, bytes(8)]}
    assert len(cbor(x5t)) == 14
    got = (
        len(message_1(0, SUITE_0, b"\x2d")),
        len(message_2(0, b"\x18", x5t)),
        len(message_3(0, x5t)),
        len(message_4()),
    )
    assert got == (37, 116, 90, 9), f"RFC 9529 trace 1: {got}"
    # Trace 2 (RFC 9529, section 3): method 3, CCSs by 'kid', ID_CRED_R = {4: h'32'},
    # ID_CRED_I = {4: h'2b'}, C_R = -8 (h'27'). Its first message_1 offers suite 6 alone, with
    # C_I = h'0e', and is refused; the second offers [6, 2], with C_I = -24 (h'37'), and suite 2
    # goes on.
    got = (
        len(message_1(3, 6, b"\x0e")),
        len(message_1(3, [6, 2], b"\x37")),
        len(message_2(3, b"\x27", {4: b"\x32"})),
        len(message_3(3, {4: b"\x2b"})),
        len(message_4()),
    )
    assert got == (37, 39, 45, 19, 9), f"RFC 9529 trace 2: {got}"


# ---------------------------------------------------------------------------------------------
# What first contact in Tern might send

# Credentials (RFC 9528, 3.5.3). By reference: a one-byte 'kid', as in RFC 9529 trace 2, which the
# receiver resolves to a key it already holds. By value: 'kccs' (label 14), a CWT Claims Set whose
# confirmation claim (8) holds the raw public key as a COSE_Key (kty OKP, crv X25519 or Ed25519 -
# both one-byte values - and the 32-byte x). No subject or other claims: a Tern address is the key.
KID = {4: b"\x05"}


def ccs(crv: int) -> dict:
    return {14: {8: {1: {1: 1, -1: crv, -2: bytes(32)}}}}


X25519, ED25519 = 4, 6

# The first-contact frame (draft/first-contact.md): the 11-byte head every frame that follows a
# route starts with, a 4-byte tag the two ends match on, and no Tern AEAD tag, because EDHOC
# protects its own messages. message_1's frame also carries the initiator's 4-byte routing id.
FRAME_PREFIX = 15
SOURCE = 4
MAX_FRAME = 255

C_I, C_R = b"\x0a", b"\x0b"  # one-byte connection identifiers, sent as integers

# (key, name, method, ID_CRED_I, ID_CRED_R). Static DH (method 3) needs X25519 identity keys;
# signatures (method 0) need Ed25519 ones.
CASES = [
    ("dh-kid", "Static DH, both known: each names the other's key by `kid`", 3, KID, KID),
    (
        "dh-first",
        "Static DH, first contact: the initiator knows the responder's address and sends its own key",
        3,
        ccs(X25519),
        KID,
    ),
    ("dh-value", "Static DH, both send their keys", 3, ccs(X25519), ccs(X25519)),
    (
        "sig-first",
        "Signatures, first contact: as `dh-first`, with Ed25519 signatures",
        0,
        ccs(ED25519),
        KID,
    ),
    ("sig-value", "Signatures, both send their keys", 0, ccs(ED25519), ccs(ED25519)),
]


def frames(method, id_cred_i, id_cred_r):
    """Frame lengths for message_1 to message_4."""
    msgs = (
        message_1(method, SUITE_0, C_I),
        message_2(method, C_R, id_cred_r),
        message_3(method, id_cred_i),
        message_4(),
    )
    return [FRAME_PREFIX + (SOURCE if i == 0 else 0) + len(m) for i, m in enumerate(msgs)], [len(m) for m in msgs]


# ---------------------------------------------------------------------------------------------
# Time on air: the firmware's integer arithmetic (ternmesh/firmware, src/lora.c), line for line

NS_PER_S = 10**9


def ldro(sf: int, bw: int) -> bool:
    return (1 << sf) * 1000 >= bw * 16  # a symbol of 16 ms or longer


def _quarters_to_ns(sf: int, bw: int, quarters: int) -> int:
    num = quarters * (1 << sf) * NS_PER_S
    den = bw * 4
    return (num + den // 2) // den


def payload_symbols(sf, bw, cr, length, crc=True, implicit=False) -> int:
    bits = 8 * length - 4 * sf + 28 + (16 if crc else 0) - (20 if implicit else 0)
    per_block = 4 * (sf - (2 if ldro(sf, bw) else 0))
    blocks = -(-bits // per_block) if bits > 0 else 0
    return 8 + blocks * (cr + 4)


def airtime(sf: int, bw: int, length: int, cr: int = 1, preamble: int = 16) -> int:
    assert 7 <= sf <= 12 and 0 <= length <= MAX_FRAME
    quarters = 4 * preamble + 17 + 4 * payload_symbols(sf, bw, cr, length)
    return _quarters_to_ns(sf, bw, quarters)


def check_airtime():
    """The firmware's and the simulator's reference table (tests/lora.c in both)."""
    cases = [
        (7, 125000, 1, 8, 16, 51456000),
        (7, 125000, 1, 8, 64, 118016000),
        (7, 125000, 1, 8, 200, 317696000),
        (11, 125000, 1, 8, 16, 659456000),
        (12, 125000, 1, 8, 200, 7217152000),
        (12, 500000, 1, 8, 64, 616448000),
        (12, 250000, 1, 8, 200, 3608576000),
        (10, 62500, 1, 8, 64, 1724416000),
        (11, 250000, 1, 16, 200, 1746944000),
        (11, 500000, 4, 16, 200, 1328128000),
        (7, 125000, 1, 8, 0, 25856000),
        (12, 125000, 4, 8, 255, 14032896000),
        (9, 250000, 2, 12, 16, 98816000),
    ]
    for sf, bw, cr, pre, n, ns in cases:
        got = airtime(sf, bw, n, cr, pre)
        assert got == ns, f"airtime SF{sf}/{bw} CR{cr} pre {pre} {n} B: {got} != {ns}"


# ---------------------------------------------------------------------------------------------
# Regions
#
# From the LoRa Alliance's Regional Parameters (RP002-1.0.4, 2022), which summarise each region's
# rules for LoRa, and where it does not give the rule, from the rule itself: 47 CFR 15.247 for the
# US, ERC Recommendation 70-03 for the EU's 10% band. Tern is not LoRaWAN, so where
# RP002 only says what LoRaWAN chose (its data rates), the rule is what binds; RP002's slowest data
# rate is used as each region's slowest setting because it is the slowest that region's devices
# are commonly certified and deployed at. Tern's own region profiles are not decided; this is not
# legal advice.
#
# (key, name, bandwidth, slowest SF, dwell limit in ns or None, duty cycle or None, source)

MS = 1_000_000
REGIONS = [
    ("eu1", "EU868, 868.0-868.6 MHz", 125000, 12, None, 0.01, "RP002 2.4: under 1% on its default channels, no dwell limit; DR0 is SF12"),
    ("eu10", "EU868, 869.4-869.65 MHz", 125000, 12, None, 0.10, "ERC Recommendation 70-03, Annex 1: 500 mW, under 10%; RP002 2.4: no dwell limit"),
    (
        "us125",
        "US915, 125 kHz, hopping",
        125000,
        10,
        400 * MS,
        None,
        "47 CFR 15.247(a)(1)(i): 0.4 s on any one channel; RP002 2.5: DR0 is SF10",
    ),
    (
        "us500",
        "US915, 500 kHz",
        500000,
        12,
        None,
        None,
        "47 CFR 15.247(a)(2): digital modulation, no dwell limit; RP002 2.5: DR8 is SF12",
    ),
    (
        "as923",
        "AS923 and AU915, where dwell applies",
        125000,
        10,
        400 * MS,
        None,
        "RP002 2.8, 2.10: where UplinkDwellTime is 1 (400 ms), which is country by country, DR2, SF10, is the slowest",
    ),
    ("kr920", "KR920", 125000, 12, 4000 * MS, None, "RP002 2.11.6: under 4 s per frame, with LBT"),
    ("in865", "IN865", 125000, 12, None, None, "RP002 2.12: no dwell or duty cycle limit"),
    ("ru864", "RU864", 125000, 12, None, 0.01, "RP002 2.13: under 1% on its default channels, no dwell limit"),
    ("eu433", "EU433", 125000, 12, None, 0.10, "RP002 2.7: under 10%, no dwell limit"),
    (
        "cn470",
        "CN470",
        125000,
        12,
        1000 * MS,
        None,
        "RP002 2.9.2: a transmission may not exceed one second, so at SF12 (DR0) LoRaWAN carries nothing",
    ),
]
# CN779 is left out: RP002 2.6 deprecates it, and no new devices may be installed.

PREAMBLES = (16, 8)  # the draft's example uses 16; the firmware's default is 8


def slowest_fitting(bw, sf_max, dwell, frame, preamble):
    """The slowest SF, at most sf_max, at which the frame fits under the dwell limit, or None."""
    if frame > MAX_FRAME:
        return None
    for sf in range(sf_max, 6, -1):
        if dwell is None or airtime(sf, bw, frame, preamble=preamble) <= dwell:
            return sf
    return None


def max_frame(bw, sf, dwell, preamble):
    """The longest frame that fits at this SF under the dwell limit, or -1 if none does."""
    n = MAX_FRAME
    while n >= 0 and dwell is not None and airtime(sf, bw, n, preamble=preamble) > dwell:
        n -= 1
    return n


# ---------------------------------------------------------------------------------------------
# The report


def ms(ns: int) -> str:
    return f"{ns / MS:,.0f}"


def report() -> str:
    out = []
    w = out.append

    w("### Message sizes\n")
    w(
        "Bytes of each EDHOC message, and in brackets the frame that carries it, "
        f"with the {FRAME_PREFIX}-byte prefix. `message_4` is optional (see below).\n"
    )
    w("| Case | `message_1` | `message_2` | `message_3` | `message_4` |")
    w("|---|---|---|---|---|")
    sized = {}
    for key, name, method, ici, icr in CASES:
        fr, raw = frames(method, ici, icr)
        sized[key] = fr
        cells = " | ".join(f"{r} ({f})" for r, f in zip(raw, fr))
        w(f"| `{key}`: {name} | {cells} |")
    w("")

    w("### Regions with a dwell limit\n")
    w(
        "The longest frame each region's slowest setting can carry, and the slowest spreading "
        "factor at which every frame of the handshake fits, `message_4` included. "
        "CR 4/5, explicit header, CRC on. Preamble 16 symbols, and 8 after the slash.\n"
    )
    head = "| Region | Slowest | Longest frame |" + "".join(f" `{k}` |" for k, *_ in CASES)
    w(head)
    w("|---|---|---|" + "---|" * len(CASES))
    for key, name, bw, sf_max, dwell, duty, src in REGIONS:
        if dwell is None:
            continue
        longest = " / ".join(f"{max_frame(bw, sf_max, dwell, p)} B" for p in PREAMBLES).replace(
            "-1 B", "none"
        )
        row = f"| {name} | SF{sf_max}/{bw // 1000} | {longest} |"
        for ckey, *_ in CASES:
            fr = sized[ckey]
            parts = []
            for p in PREAMBLES:
                sfs = [slowest_fitting(bw, sf_max, dwell, f, p) for f in fr]
                parts.append("none" if None in sfs else f"SF{min(sfs)}")
            row += " " + " / ".join(parts) + " |"
        w(row)
    w("")

    w("### Regions without one\n")
    w(
        "Every frame fits at the slowest setting, so what matters is time on air: "
        "milliseconds each side transmits for the handshake (initiator: messages 1 and 3; "
        "responder: message 2, and 4 if sent), at a 16-symbol preamble. Where there is a duty "
        "cycle, the share of one hour's allowance that is.\n"
    )
    w("| Region | Slowest | Case | Initiator, ms | Responder, ms (+ `message_4`) | Share of the hour |")
    w("|---|---|---|---|---|---|")
    for key, name, bw, sf_max, dwell, duty, src in REGIONS:
        if dwell is not None and dwell < airtime(sf_max, bw, MAX_FRAME):
            continue
        for ckey, *_ in CASES:
            fr = sized[ckey]
            t = [airtime(sf_max, bw, f) for f in fr]
            ini, resp = t[0] + t[2], t[1]
            share = "-"
            if duty is not None:
                allowance = 3600 * NS_PER_S * duty
                share = f"{100 * ini / allowance:.1f}% / {100 * (resp + t[3]) / allowance:.1f}%"
            w(
                f"| {name} | SF{sf_max}/{bw // 1000} | `{ckey}` | {ms(ini)} | "
                f"{ms(resp)} (+{ms(t[3])}) | {share} |"
            )
    w("")

    w("### Sources for each region\n")
    for key, name, bw, sf_max, dwell, duty, src in REGIONS:
        w(f"* **{name}:** {src}.")
    return "\n".join(out) + "\n"


def splice(doc: str, body: str) -> str:
    before, rest = doc.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    return before + BEGIN + "\n\n" + body + "\n" + END + after


def check_lorawan():
    """The longest frames under a dwell limit match the PHY payloads RP002 allows: its MACPayload
    limit M plus LoRaWAN's 5 bytes of framing, at LoRaWAN's 8-symbol preamble."""
    us_dr0 = max_frame(125000, 10, 400 * MS, 8)
    assert us_dr0 == 19 + 5, f"US915 DR0: {us_dr0}"  # RP002 2.5.6
    cn470 = [max_frame(125000, sf, 1000 * MS, 8) for sf in (11, 10, 9)]
    assert cn470 == [31 + 5, 94 + 5, 192 + 5], f"CN470 DR1-3: {cn470}"  # RP002 2.9.6, Table 45


def main(argv):
    check_rfc9529()
    check_airtime()
    check_lorawan()
    cmd = argv[1] if len(argv) > 1 else "report"
    body = report()
    if cmd == "report":
        sys.stdout.write(body)
    elif cmd == "update":
        DOC.write_text(splice(DOC.read_text(), body))
    elif cmd == "check":
        doc = DOC.read_text()
        if splice(doc, body) != doc:
            sys.exit(f"{DOC.name} is out of date: run `python3 analysis/{Path(__file__).name} update`")
        print(f"{DOC.name} is up to date")
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main(sys.argv)
